service-monitoring/src/table.ihtml
Replace never_chek.png by never_checked.png
=> Wrong name for file .png

service-monitoring/configs.xml, service-monitoring/src/index.php
- Patch added in centreon 2.7.2 centreon/centreon#4165 is used
- Use instances table (and not instance table)
=> Add function to filter alerts by poller

service-monitoring/src/index.php
Links should work like in the status view of centreon:
- Entire URL: http://...
- Only suffix: /site
=> Action URL & notes URL are not correctly built

service-monitoring/src/action.php, service-monitoring/src/toolbar.php
#67
Problem about ACL actions is solved.
=> fix(ACL): Fix ACL actions

service-monitoring/index.php, service-monitoring/src/index.php
Fix loading of smarty and deprecated functions.
=> Cp7 m27 php7 update fixes

service-monitoring/data.js, service-monitoring/index.php, service-monitoring/src/action.php, service-monitoring/src/data_js.js, service-monitoring/src/export.php, service-monitoring/src/index.php, service-monitoring/src/sendCmd.php, service-monitoring/src/toolbar.php
Last check, Duration and Hard state Duration
Resolve CP7M-80
=> feat(widget): better display of datetime columns

service-monitoring/src/index.php
Fix double quotes and formatting. Update the action and note URL regex. Fix the binded parameters value.
=> Cp7 m79 fix action url column

service-monitoring/src/index.php
when service is in downtime show information from downtime table
Resolve CP7M-81
Ref entreon/centreon#5773
=> feat(widget): show last comment from downtime table

service-monitoring/src/index.php
Show acknowledgement comment for the service.
=> feat(widget): show acknowledgement comment

service-monitoring/data.js, service-monitoring/src/data_js.js
=> fix(front): resize properly widget after data load

service-monitoring/src/index.php
Modified how to calculate the total number of lines
=> fix(pagination): Fix non-visible pagination

service-monitoring/src/action.php, service-monitoring/src/downtime.ihtml, service-monitoring/src/sendCmd.php
=> MON-3133-fix-dt-datepicker-timepicker-and-external_cmd

service-monitoring/configs.xml, service-monitoring/src/index.php
=> enh(UI): replacing select with select2

service-monitoring/src/data_js.js
=> enh(widgets): use localStorage to keep checked checkboxes during refresh

service-monitoring/configs.xml, service-monitoring/data.js, service-monitoring/src/index.php, service-monitoring/src/table.ihtml
correct hard state and last hard state wrong format durations
=> fix(UI): correct duration columns

service-monitoring/src/action.php, service-monitoring/src/downtime.ihtml, service-monitoring/src/index.ihtml
Fix datepicker DT in the popin
=> fix(datepicker): change end date when start date is set after it

service-monitoring/src/export.php
=> fix export when filtering on hostrgoup

service-monitoring/data.js, service-monitoring/index.php, service-monitoring/src/action.php, service-monitoring/src/data_js.js, service-monitoring/src/export.php, service-monitoring/src/index.php, service-monitoring/src/sendCmd.php, service-monitoring/src/toolbar.php
- Sanitizing http parameters to avoid injections
- Cleaning code or style
For :
2.8.x
=> fix(security): sanitize against injection

service-monitoring/configs.xml
change version number to be able to release a new widget with cherry-picked modifications
=> change version number

service-monitoring/data.js, service-monitoring/index.php, service-monitoring/src/export.php, service-monitoring/src/index.ihtml, service-monitoring/src/index.php, service-monitoring/src/sendCmd.php, service-monitoring/src/toolbar.php
Export only the selected resources in the CSV file
Add a warning when less than 1 resource is selected
Add checks and sanitize different parameters
19.10.x
20.04.x
fixes: (MON-5010)
=> enh: export only selected resources

service-monitoring/src/index.php, service-monitoring/src/table.ihtml
redirect hosts & services to resource details panel
/!\ waiting https://github.com/centreon/centreon/pull/8984 to be merged
**Fixes** MON-5657
<h2> How this pull request can be tested ? </h2>
Click on a host
==> check redirection to resource panel details of the host
Click on a service
==> check redirection to resource panel details of the service
=> enh(ui): redirect hosts & services to resource details panel

service-monitoring/src/toolbar.php
unselect checkbox after sending external command
Replace #154 
Refs: MON-5882
thanks @tanguyvda
=> fix(ui): unselect checkbox after sending external command

service-monitoring/configs.xml
=> chore(install): update version to 19.10.7

service-monitoring/configs.xml
=> chore(install): update version to 20.04.4

Jenkinsfile, service-monitoring/configs.xml
preparing version 21.04.0 for widget centreon-widget-service-monitoring
=> chore(install): update version to 21.04.0

.gitignore, Jenkinsfile, composer.json, composer.lock, ruleset.xml, service-monitoring/index.php, service-monitoring/src/action.php, service-monitoring/src/export.php, service-monitoring/src/index.php, service-monitoring/src/sendCmd.php, service-monitoring/src/toolbar.php, sonar-project.properties
Add requirements to be able to implement githubviolation, sonarQube analysis, coverage and codestyle
**Fixes** # (MON-6425)
linked to : https://github.com/centreon/centreon-build/pull/384
=> enh(chore): add CI requirements for github violation

.github/PULL_REQUEST_TEMPLATE.md, Jenkinsfile, composer.json, service-monitoring/configs.xml
=> chore(version): prepare 21.10 serie
